### ISSUE TITLE
The tool do not provide up-to date language statistic.

### ISSUE THREAD

**Issue by fogfish** [zalando-incubator/zalando.github.io-dev#18]
API should return Scala

https://catwatch.opensource.zalan.do/statistics/languages?organizations=zalando,zalando-stups,zalando-techmonkeys

API should return Erlang
https://catwatch.opensource.zalan.do/languages?organizations=zalando,zalando-stups,zalando-techmonkeys&limit=50&offset=0

**Comment by rbarilani** [comment]
Oh sorry @fogfish, this is just the frontend project for the zalando github.io page.
For issue about incorrect data response from the rest api... https://github.com/zalando/catwatch
