### ISSUE TITLE
Projects plot date order

### ISSUE THREAD

**Issue by rbobin** [zalando-incubator/zalando.github.io-dev#20]
Date order is broken for Projects plot, check the screenshot
![screenshot 2015-11-26 11 17 46](https://cloud.githubusercontent.com/assets/1652657/11420830/06e640a8-9431-11e5-8983-a3f422035dbe.png)

**Comment by rbarilani** [comment]
@rbobin Hi Roman, yep we have problems with the plot, we will disable it for now.
related to #19 #16
