### ISSUE TITLE
First 6 projects shown twice

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando-incubator/zalando.github.io-dev#23]
Open
http://zalando.github.io/

See first 6 projects repeated twice. May depend on screen height I think

**Comment by hjacobs** [comment]
shouldn't this issue be in the https://github.com/zalando/catwatch repo?

**Comment by AlexanderYastrebov** [comment]
@hjacobs It looks like frontend issue

**Comment by hjacobs** [comment]
Yes, correct, the REST API returns results with correct paging.

**Comment by rbarilani** [comment]
Yep confirmed. It's a problem of the infine scroll plugin/component that fires twice with the same page.... I'm fixing it on my fork.. stay tuned.
