### ISSUE TITLE
Language filter should have "Others"

### ISSUE THREAD

**Issue by ePaul** [zalando-incubator/zalando.github.io-dev#27]
Currently [the repository list](http://zalando.github.io/#repositories) has some language filters above it (currently Python, JavaScript, Java, Shell, Clojure). I heard those are the most used ones, but anyways there are several repositories which have neither of the mentioned languages as their "main language" (I found Go, Swift, CSS, Coffeescript, Scala, PLPGSQL, "Unknown", Ruby, Makefile, C++, Erlang, Typescript, PHP).

Finding them in the "All" view is a bit cumbersome – therefore I propose having an "Other" filter which lists just repositories in languages which are not one of the languages with a specific filter.

**Comment by rbarilani** [comment]
@ePaul Ok... finally we can offer a solution for this issue, please check the dev preview: https://github.com/zalando-incubator/zalando.github.io-dev and tell us what you think?

**Comment by ePaul** [comment]
@rbarilani I guess you mean this one? http://zalando-incubator.github.io/zalando.github.io-dev/#repositories

This is not quite what I thought about, but better than before, assuming one knows for which language one is looking. (It doesn't help when one doesn't know which language is searched, but I'm not sure how often that use case is.)

PS: I noted that some repositories have an "unknown" language, but I can't filter for those.

**Comment by rbarilani** [comment]
@ePaul Yep I meant that one ;-).

Well we thought that for the user is interesting to check if zalando has some projects written in his/her favourite language. 

>  PS: I noted that some repositories have an "unknown" language, but I can't filter for those.

Yep. true... thanks for pointing out this thing.

**Comment by rbarilani** [comment]
Closed with #50
