### ISSUE TITLE
Show project "title" instead of "name" (if possible)

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/zalando.github.io-dev#30]
We implemented a new feature in Catwatch (https://github.com/zalando/catwatch/issues/32) to scan for `.catwatch.yaml` files containing optional `title` and `image` for GitHub projects.

The frontend should show the human readable "title" instead of the simple repository name if it was set.

**Comment by rbarilani** [comment]
@hjacobs Yep. Title MAY exists, right?

**Comment by hjacobs** [comment]
Yes, the "title" is optional (the repo needs a `.catwatch.yaml` for this) --- you can check here: https://catwatch.opensource.zalan.do/projects?organizations=zalando,zalando-stups,zalando-techmonkeys&limit=6&offset=0&sortBy=-score

(New version of catwatch was deployed including "maintainers", "title" and "image".)

**Comment by hjacobs** [comment]
@rbarilani any update on this? It should be a small change, right? :smirk:

**Comment by rbarilani** [comment]
@hjacobs Yes it is. On Monday I will be back in office and I will take care of this issue. Sorry for the delay but in the previous weeks I was working hard on another project. https://github.com/zalando/dress-code

**Comment by hjacobs** [comment]
@rbarilani no problem, thanks!

**Comment by hjacobs** [comment]
Great, thanks :tada:
