### ISSUE TITLE
Add "zalando-zmon" GitHub organization to configuration

### ISSUE THREAD

**Issue by hjacobs** [zalando-incubator/zalando.github.io-dev#48]
"zalando-zmon" needs to be added to `src/config/parameters.default.json` as ZMON repositories move to the new organization.

**Comment by hjacobs** [comment]
@rbarilani could you do this? I feel a bit helpless regarding the development and deployment process...

**Comment by rbarilani** [comment]
@hjacobs Ok I will as soon as possible...obviously zalando-zmon data is already collected by catwatch?

**Comment by hjacobs** [comment]
@rbarilani yes, it's already collected by Catwatch: https://catwatch.opensource.zalan.do/statistics?organizations=zalando-zmon

I just want to have the change in zalando.github.io before moving the other 10+ repositories :smirk:

**Comment by rbarilani** [comment]
closed with #49

**Comment by hjacobs** [comment]
:+1: thanks.
