### ISSUE TITLE
[Research] Update knowledge what data points are possible

### ISSUE THREAD

**Issue by fokusferit** [zalando-incubator/zalando.github.io-dev#70]
This research task is an initial discovery what the current Github API is providing us in terms of analytics, data, etc. for each of our projects. 
Additionally, checking in with the people from Catwatch makes also sense as they might provide / plan new features.

- [x] What kind of data does Github API provide us to show additional metrics and visualization ?
- [x] Is catwatch providing additional features ?

**Comment by fokusferit** [comment]
- Talk to Alexander Kops, pitch our vision for v2 and ask him if he has time + interest helping / joining us
- We might need more from Github API for repositories, therefore we need to extend catwatch to provide us more time-based data , so we can show more timeline based data.
- (check gdocs for details)

**Comment by rbarilani** [comment]
@fokusferit I talked with @alexkops. He's in. I will invite him to our short recurring meetings.

**Comment by fokusferit** [comment]
#bäm 🎆
